Fix python namespace packaging + Flashlight pkgs (#4)
Summary:
See title. Stop using `namespace_packages` since it's deprecated, and follow the official docs which stipulate removing `__init__.py` from every namespace dir that doesn't actually have package assets.

Pull Request resolved: https://github.com/flashlight/sequence/pull/4

Test Plan:
tested install combos, i.e.
text:
```
conda create -n flashlight-python python=3.10
conda activate flashlight-python
cd text/bindings/python
USE_KENLM=0 python setup.py install
```
sequence:
```
cd sequence/bindings/python
USE_CUDA=0 python setup.py install
```
then test incremental install
```
python
> from flashlight.lib.text import decoder
> from flashlight.lib.sequence import criterion
```
then remove things:
```
pip uninstall flashlight-text
python
> from flashlight.lib.sequence import criterion
```
remove everything
```
pip uninstall flashlight-sequence
python
> import flashlight
>> ModuleNotFoundError: No module named 'flashlight'
```

Reviewed By: bwasti

Differential Revision: D41377635

Pulled By: jacobkahn

fbshipit-source-id: e3e4eb349ed924a47ebf47b5e93529fe08574c34